[project]
name = "firetower"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.5",
]

[dependency-groups]
dev = [
    "pyupgrade>=3.20.0",
    "ruff>=0.12.11",
    "ty>=0.0.1a19",
]
